export const TOUR_INFO = {
  title: "이탈리아 아트 투어 9일",
  productCode: "EWQ111260626TW5",
  startDate: "2026-06-26",
  endDate: "2026-07-04",
  flightOutbound: "TW0405",
  flightInbound: "TW0406",
  airline: "티웨이항공",
  guideFeeEur: 90,
  kakaoUrl: "http://pf.kakao.com/_gIxlNb/chat",
};

export type Category =
  | "flight"
  | "transport"
  | "sight"
  | "meal"
  | "optional"
  | "hotel";

export interface Spot {
  id: string;
  category: Category;
  time?: string;
  nameKo: string;
  nameEn?: string;
  city?: string;
  description?: string;
  imagePath?: string;
  googleMapsUrl?: string;
  isInsideVisit?: boolean;
  duration?: string;
  priceEur?: number;
  youtubeUrls?: { title: string; url: string }[];
}

export interface DayData {
  dayNumber: number;
  date: string;
  dayOfWeek: string;
  routeSummary: string;
  totalTravelTime?: string;
  breakfast: string;
  lunch: string;
  dinner: string;
  accommodationName: string;
  accommodationGrade: string;
  accommodationStatus: "확정" | "예정";
  accommodationMapsUrl?: string;
  spots: Spot[];
}

function mapsUrl(query: string) {
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;
}

export const DAYS: DayData[] = [
  {
    dayNumber: 1,
    date: "2026-06-26",
    dayOfWeek: "금",
    routeSummary: "인천 → 로마",
    breakfast: "기내식",
    lunch: "기내식",
    dinner: "기내식",
    accommodationName: "호텔 팰리스 2000 (4성급)",
    accommodationGrade: "4성급",
    accommodationStatus: "확정",
    accommodationMapsUrl: mapsUrl("Palace 2000 Hotel Rome"),
    spots: [
      {
        id: "d1-0",
        category: "transport",
        time: "09:35",
        nameKo: "인천공항 T1 미팅 (선택)",
        city: "인천",
        description: "인솔자와 미리 만나고 싶은 분은 09:35 인천공항 제1터미널로 오세요. 꼭 모두 모여야 하는 것은 아닙니다. 개별 수속이 가능한 분은 각자 진행하신 후 게이트에서 만나셔도 됩니다.",
      },
      {
        id: "d1-1",
        category: "flight",
        time: "12:35",
        nameKo: "인천국제공항 출발",
        nameEn: "Incheon International Airport",
        city: "인천",
        description: "티웨이항공 TW0405편으로 로마 피우미치노 공항으로 출발합니다. 직항 비행 13시간 40분.",
        imagePath: "/images/day1-cover.jpg",
        googleMapsUrl: mapsUrl("Incheon International Airport"),
        duration: "비행 13시간 40분",
      },
      {
        id: "d1-2",
        category: "flight",
        time: "19:15",
        nameKo: "로마 피우미치노 공항 도착",
        nameEn: "Rome Fiumicino Airport FCO",
        city: "로마",
        description: "현지 시각 19:15 로마 도착. 가이드 미팅 후 호텔로 이동합니다.",
        imagePath: "/images/day1-cover.jpg",
        googleMapsUrl: mapsUrl("Rome Fiumicino Airport FCO"),
      },
    ],
  },
  {
    dayNumber: 2,
    date: "2026-06-27",
    dayOfWeek: "토",
    routeSummary: "로마 → 피렌체",
    breakfast: "호텔식",
    lunch: "현지식(피오렌티나 스테이크)",
    dinner: "현지식",
    accommodationName: "베스트 웨스턴 호텔 트레 토리 (4성급)",
    accommodationGrade: "4성급",
    accommodationStatus: "확정",
    accommodationMapsUrl: mapsUrl("Best Western Hotel Tre Torri Vicenza"),
    spots: [
      {
        id: "d2-1",
        category: "transport",
        nameKo: "로마 → 피렌체 이동",
        duration: "약 4시간 소요",
        description: "전용 버스로 로마에서 피렌체로 이동합니다.",
      },
      {
        id: "d2-2",
        category: "meal",
        nameKo: "중식 · 피오렌티나 스테이크",
        city: "피렌체",
        description: "토스카나 지방의 대표 음식, 두꺼운 티본 스테이크 피오렌티나. 키아니나 소고기로 만든 정통 요리.",
        imagePath: "/images/food/fiorentina-steak.jpg",
      },
      {
        id: "d2-3",
        category: "sight",
        time: "13:00",
        nameKo: "팔라쪼 스트로치 — 마크 로스코 & 프라 안젤리코 특별전",
        nameEn: "Palazzo Strozzi",
        city: "피렌체",
        description: "15세기 르네상스 궁전 팔라쪼 스트로치에서 열리는 특별전. 색채의 거장 마크 로스코와 초기 르네상스의 빛 프라 안젤리코의 작품을 한자리에서 감상합니다.",
        imagePath: "/images/florence/palazzo-strozzi.jpg",
        googleMapsUrl: mapsUrl("Palazzo Strozzi Florence"),
        isInsideVisit: true,
        youtubeUrls: [
          { title: "마크 로스코", url: "https://www.youtube.com/embed/eNBsKrSOnO8" },
        ],
      },
      {
        id: "d2-4",
        category: "sight",
        time: "15:00",
        nameKo: "우피치 미술관",
        nameEn: "Uffizi Gallery",
        city: "피렌체",
        description: "세계 최고의 르네상스 미술관. 보티첼리의 '비너스의 탄생', 레오나르도 다빈치, 미켈란젤로의 걸작을 소장. 내부 입장.",
        imagePath: "/images/florence/uffizi.jpg",
        googleMapsUrl: mapsUrl("Uffizi Gallery Florence"),
        isInsideVisit: true,
        youtubeUrls: [
          { title: "우피치 미술관", url: "https://www.youtube.com/embed/wf1BgcbIEwk" },
          { title: "카라바조", url: "https://www.youtube.com/embed/iQq6dWqToF8" },
        ],
      },
      {
        id: "d2-5",
        category: "sight",
        time: "18:00",
        nameKo: "미켈란젤로 언덕 (피아잘레 미켈란젤로)",
        nameEn: "Piazzale Michelangelo",
        city: "피렌체",
        description: "피렌체 시가지 전체가 한눈에 내려다보이는 전망대. 저녁 노을 속 두오모와 베키오 궁전의 절경을 감상합니다.",
        imagePath: "/images/florence/piazzale-michelangelo.jpg",
        googleMapsUrl: mapsUrl("Piazzale Michelangelo Florence"),
        youtubeUrls: [
          { title: "피렌체 여행 총정리", url: "https://www.youtube.com/embed/pQp-mq0z4qw" },
        ],
      },
      {
        id: "d2-6",
        category: "meal",
        time: "18:30",
        nameKo: "석식 · 현지식",
        city: "피렌체",
        description: "피렌체 현지 레스토랑에서 저녁 식사.",
      },
      {
        id: "d2-7",
        category: "transport",
        nameKo: "호텔로 이동",
        description: "숙소로 이동합니다.",
      },
    ],
  },
  {
    dayNumber: 3,
    date: "2026-06-28",
    dayOfWeek: "일",
    routeSummary: "베네치아 — 페기 구겐하임 미술관 · 베니스 비엔날레",
    breakfast: "호텔식",
    lunch: "자유식 (인당 EUR 10 제공)",
    dinner: "현지식 (양식)",
    accommodationName: "Roy Hotel (4성급)",
    accommodationGrade: "4성급",
    accommodationStatus: "확정",
    accommodationMapsUrl: mapsUrl("Roy Hotel Treviso"),
    spots: [
      {
        id: "d3-1",
        category: "sight",
        time: "오전",
        nameKo: "페기 구겐하임 미술관",
        nameEn: "Peggy Guggenheim Collection",
        city: "베네치아",
        description: "20세기 현대미술의 보고. 피카소, 달리, 칸딘스키, 폴록 등 거장들의 작품이 운하 옆 팔라초에 전시된 세계적인 미술관. 내부 입장.",
        imagePath: "/images/venice/peggy-guggenheim.jpg",
        googleMapsUrl: mapsUrl("Peggy Guggenheim Collection Venice"),
        isInsideVisit: true,
      },
      {
        id: "d3-2",
        category: "sight",
        time: "오후",
        nameKo: "베니스 비엔날레 — 자르디니",
        nameEn: "Venice Biennale - Giardini",
        city: "베네치아",
        description: "1895년 시작된 세계 최고 권위의 현대미술 축제. 자르디니 공원의 각국 국가관에서 세계 각지의 현대미술 작품을 감상합니다. 내부 입장.",
        imagePath: "/images/venice/biennale-giardini.jpg",
        googleMapsUrl: mapsUrl("Giardini della Biennale Venice"),
        isInsideVisit: true,
      },
      {
        id: "d3-3",
        category: "sight",
        time: "오후",
        nameKo: "베니스 비엔날레 — 아르세날레",
        nameEn: "Venice Biennale - Arsenale",
        city: "베네치아",
        description: "중세 베네치아 공화국의 거대한 조선소를 개조한 전시 공간. 비엔날레 주제전의 핵심 장소로 국제적인 현대미술 작품이 대규모로 전시됩니다. 내부 입장.",
        imagePath: "/images/venice/biennale-arsenale.jpg",
        googleMapsUrl: mapsUrl("Arsenale Venice Biennale"),
        isInsideVisit: true,
      },
      {
        id: "d3-4",
        category: "sight",
        nameKo: "베네치아 총정리",
        city: "베네치아",
        youtubeUrls: [
          { title: "베네치아 여행 총정리", url: "https://www.youtube.com/embed/QhqU9FlnCHs" },
        ],
      },
    ],
  },
  {
    dayNumber: 4,
    date: "2026-06-29",
    dayOfWeek: "월",
    routeSummary: "트레비소 → 돌로미티 (친퀘 토리 · 파쏘 지아우 하이킹)",
    totalTravelTime: "약 2시간",
    breakfast: "호텔식",
    lunch: "양식",
    dinner: "양식",
    accommodationName: "Roy Hotel (4성급)",
    accommodationGrade: "4성급",
    accommodationStatus: "확정",
    accommodationMapsUrl: mapsUrl("Roy Hotel Treviso"),
    spots: [
      {
        id: "d4-1",
        category: "transport",
        nameKo: "트레비소 → 돌로미티 이동",
        duration: "약 2시간 소요",
        description: "전용 버스로 돌로미티로 이동합니다.",
      },
      {
        id: "d4-2",
        category: "sight",
        nameKo: "친퀘 토리",
        nameEn: "Cinque Torri",
        city: "돌로미티",
        description: "유네스코 세계자연유산 돌로미티의 다섯 개 바위탑. 장엄한 석회암 봉우리들이 하늘을 찌르는 절경이 펼쳐집니다.",
        imagePath: "/images/dolomites/cinque-torri.jpg",
        googleMapsUrl: mapsUrl("Cinque Torri Dolomites"),
      },
      {
        id: "d4-3",
        category: "sight",
        nameKo: "파쏘 지아우 하이킹",
        nameEn: "Passo Giau",
        city: "돌로미티",
        description: "친퀘 토리에서 파쏘 지아우(해발 2,236m)까지 이어지는 하이킹. 돌로미티의 웅장한 파노라마를 감상하며 걷는 알프스 트레킹.",
        imagePath: "/images/dolomites/passo-giau.jpg",
        googleMapsUrl: mapsUrl("Passo Giau Dolomites"),
      },
    ],
  },
  {
    dayNumber: 5,
    date: "2026-06-30",
    dayOfWeek: "화",
    routeSummary: "트레비소 → 베네치아 → 파도바",
    totalTravelTime: "약 1시간 10분",
    breakfast: "호텔식",
    lunch: "양식",
    dinner: "양식",
    accommodationName: "모니카 호텔 피에라 (4성급)",
    accommodationGrade: "4성급",
    accommodationStatus: "확정",
    accommodationMapsUrl: mapsUrl("Monica Hotel Fiera Milan"),
    spots: [
      {
        id: "d5-1",
        category: "transport",
        nameKo: "트레비소 → 베네치아 이동",
        duration: "약 40분 소요",
        description: "베네치아로 이동합니다.",
      },
      {
        id: "d5-2",
        category: "sight",
        nameKo: "산 마르코 광장",
        nameEn: "Piazza San Marco",
        city: "베네치아",
        description: "베네치아의 심장부. 산 마르코 성당, 두칼레 궁전, 종탑이 어우러진 아름다운 광장입니다.",
        imagePath: "/images/venice/piazza-san-marco.jpg",
        googleMapsUrl: mapsUrl("Piazza San Marco Venice"),
      },
      {
        id: "d5-3",
        category: "sight",
        nameKo: "탄식의 다리",
        nameEn: "Bridge of Sighs",
        city: "베네치아",
        description: "두칼레 궁전과 감옥을 잇는 유명한 다리. 죄수들이 마지막으로 베네치아를 바라보며 탄식했다는 전설이 있습니다.",
        imagePath: "/images/venice/bridge-of-sighs.jpg",
        googleMapsUrl: mapsUrl("Bridge of Sighs Venice"),
      },
      {
        id: "d5-4",
        category: "sight",
        nameKo: "리알토 다리",
        nameEn: "Ponte di Rialto",
        city: "베네치아",
        description: "베네치아 대운하를 가로지르는 가장 오래된 다리. 16세기에 완성된 석조 아치 다리로, 다리 위에 늘어선 상점과 운하 풍경이 아름답습니다.",
        imagePath: "/images/venice/gondola.jpg",
        googleMapsUrl: mapsUrl("Ponte di Rialto Venice"),
      },
      {
        id: "d5-5",
        category: "transport",
        nameKo: "베네치아 → 파도바 이동",
        duration: "약 30분 소요",
        description: "전용 버스로 파도바로 이동합니다.",
      },
      {
        id: "d5-6",
        category: "sight",
        nameKo: "스크로베니 예배당",
        nameEn: "Cappella degli Scrovegni",
        city: "파도바",
        description: "조토 디 본도네가 1304~1306년에 그린 프레스코화로 가득한 예배당. 서양 미술사의 전환점으로 평가받는 걸작. 내부 입장.",
        imagePath: "/images/padua/scrovegni-chapel.jpg",
        googleMapsUrl: mapsUrl("Cappella degli Scrovegni Padova"),
        isInsideVisit: true,
      },
    ],
  },
  {
    dayNumber: 6,
    date: "2026-07-01",
    dayOfWeek: "수",
    routeSummary: "밀라노 → 친퀘테레 → 피사 → 몬테카티니",
    totalTravelTime: "약 5시간 20분",
    breakfast: "호텔식",
    lunch: "자유식 (EUR 10 제공)",
    dinner: "양식",
    accommodationName: "Hotel Puccini Montecatini Terme (4성급)",
    accommodationGrade: "4성급",
    accommodationStatus: "확정",
    accommodationMapsUrl: mapsUrl("Hotel Puccini Montecatini Terme"),
    spots: [
      {
        id: "d6-1",
        category: "transport",
        nameKo: "밀라노 → 라스페치아 이동",
        duration: "약 3시간 30분 소요",
        description: "친퀘테레 관문 도시 라스페치아로 이동합니다.",
      },
      {
        id: "d6-2",
        category: "sight",
        nameKo: "친퀘테레",
        nameEn: "Cinque Terre",
        city: "친퀘테레",
        description: "유네스코 세계문화유산. 절벽에 알록달록하게 붙어 있는 다섯 개의 해변 마을. 마나롤라, 리오마조레 등 아름다운 경관.",
        imagePath: "/images/cinque-terre/cinque-terre.jpg",
        googleMapsUrl: mapsUrl("Cinque Terre"),
      },
      {
        id: "d6-3",
        category: "transport",
        nameKo: "라스페치아 → 피사 이동",
        duration: "약 1시간 소요",
        description: "피사로 이동합니다.",
      },
      {
        id: "d6-4",
        category: "sight",
        nameKo: "피사의 사탑",
        nameEn: "Leaning Tower of Pisa",
        city: "피사",
        description: "세계적으로 유명한 기울어진 탑. 12세기에 착공하여 약 200년에 걸쳐 완성된 로마네스크 양식의 종탑. 외부 관광.",
        imagePath: "/images/pisa/leaning-tower.jpg",
        googleMapsUrl: mapsUrl("Leaning Tower of Pisa"),
        isInsideVisit: false,
      },
      {
        id: "d6-5",
        category: "sight",
        nameKo: "피사 두오모",
        nameEn: "Pisa Cathedral",
        city: "피사",
        description: "사탑 바로 옆에 위치한 로마네스크 양식의 대성당. 외부 관광.",
        imagePath: "/images/pisa/pisa-duomo.jpg",
        googleMapsUrl: mapsUrl("Pisa Cathedral"),
        isInsideVisit: false,
      },
      {
        id: "d6-6",
        category: "transport",
        nameKo: "피사 → 몬테카티니 테르메 이동",
        duration: "약 50분 소요",
        description: "온천으로 유명한 몬테카티니 테르메로 이동합니다.",
      },
    ],
  },
  {
    dayNumber: 7,
    date: "2026-07-02",
    dayOfWeek: "목",
    routeSummary: "몬테카티니 → 몬테풀차노 → 발도르차 → 로마",
    totalTravelTime: "약 4시간 30분",
    breakfast: "호텔식",
    lunch: "양식",
    dinner: "한식 (불판 삼겹살)",
    accommodationName: "호텔 팰리스 2000 (4성급)",
    accommodationGrade: "4성급",
    accommodationStatus: "확정",
    accommodationMapsUrl: mapsUrl("Palace 2000 Hotel Rome"),
    spots: [
      {
        id: "d7-1",
        category: "transport",
        nameKo: "몬테카티니 → 몬테풀차노 이동",
        duration: "약 2시간 소요",
        description: "토스카나 와인 마을 몬테풀차노로 이동합니다.",
      },
      {
        id: "d7-2",
        category: "sight",
        nameKo: "몬테풀차노",
        nameEn: "Montepulciano",
        city: "토스카나",
        description: "언덕 위에 자리한 중세 와인 마을. 비노 노빌레 와인으로 유명하며 와이너리 시음 포함.",
        imagePath: "/images/tuscany/montepulciano.jpg",
        googleMapsUrl: mapsUrl("Montepulciano"),
      },
      {
        id: "d7-3",
        category: "meal",
        nameKo: "와이너리 시음",
        city: "몬테풀차노",
        description: "몬테풀차노의 와이너리에서 토스카나 와인 시음. 비노 노빌레 등 지역 특산 와인을 맛봅니다.",
        imagePath: "/images/tuscany/tuscany-wine.jpg",
      },
      {
        id: "d7-4",
        category: "sight",
        nameKo: "발도르차 평원",
        nameEn: "Val d'Orcia",
        city: "토스카나",
        description: "유네스코 세계문화유산. 사이프러스 나무가 늘어선 구불구불한 길과 황금빛 언덕이 그림 같은 토스카나의 상징적 풍경.",
        imagePath: "/images/tuscany/val-dorcia.jpg",
        googleMapsUrl: mapsUrl("Val d'Orcia"),
      },
      {
        id: "d7-5",
        category: "transport",
        nameKo: "발도르차 → 로마 이동",
        duration: "약 2시간 30분 소요",
        description: "로마로 귀환합니다.",
      },
    ],
  },
  {
    dayNumber: 8,
    date: "2026-07-03",
    dayOfWeek: "금",
    routeSummary: "로마 시내 관광 → 로마 출발",
    breakfast: "호텔식",
    lunch: "양식",
    dinner: "기내식",
    accommodationName: "기내",
    accommodationGrade: "",
    accommodationStatus: "확정",
    spots: [
      {
        id: "d8-1",
        category: "sight",
        nameKo: "바티칸 박물관",
        nameEn: "Vatican Museums",
        city: "바티칸",
        description: "세계 최대 규모의 박물관 중 하나. 우선입장 티켓으로 대기 없이 입장. 미켈란젤로의 시스티나 예배당 천장화와 라파엘로의 방 등 르네상스 걸작을 감상합니다. 내부 입장.",
        imagePath: "/images/rome/vatican-museums.jpg",
        googleMapsUrl: mapsUrl("Vatican Museums Rome"),
        isInsideVisit: true,
        youtubeUrls: [
          { title: "바티칸 박물관 (채수한 가이드)", url: "https://www.youtube.com/embed/sJLXGq84-rs" },
          { title: "바티칸 박물관 (안현배 사학자)", url: "https://www.youtube.com/embed/drEN8GsJQgg" },
        ],
      },
      {
        id: "d8-2",
        category: "sight",
        nameKo: "성 베드로 대성당",
        nameEn: "St Peter's Basilica Vatican",
        city: "바티칸",
        description: "세계 최대 규모의 가톨릭 성당. 미켈란젤로가 설계한 거대한 돔이 로마 하늘을 수놓습니다. 외부 관광.",
        imagePath: "/images/rome/st-peters-basilica.jpg",
        googleMapsUrl: mapsUrl("St Peter's Basilica Vatican"),
        isInsideVisit: false,
      },
      {
        id: "d8-3",
        category: "sight",
        nameKo: "포폴로 광장",
        nameEn: "Piazza del Popolo",
        city: "로마",
        description: "로마의 북쪽 관문. 이집트 오벨리스크를 중심으로 한 웅장한 광장.",
        imagePath: "/images/rome/piazza-popolo.jpg",
        googleMapsUrl: mapsUrl("Piazza del Popolo Rome"),
      },
      {
        id: "d8-4",
        category: "sight",
        nameKo: "스페인 광장",
        nameEn: "Piazza di Spagna",
        city: "로마",
        description: "로마에서 가장 유명한 광장 중 하나. 138개의 계단으로 이루어진 스페인 계단과 바르카차 분수가 있는 낭만적인 장소.",
        imagePath: "/images/rome/spanish-steps.jpg",
        googleMapsUrl: mapsUrl("Piazza di Spagna Rome"),
      },
      {
        id: "d8-5",
        category: "sight",
        nameKo: "판테온",
        nameEn: "Pantheon",
        city: "로마",
        description: "서기 125년 하드리아누스 황제가 재건한 고대 로마의 신전. 직경 43m의 거대한 돔 천장에 뚫린 오쿨루스가 인상적입니다.",
        imagePath: "/images/rome/pantheon.jpg",
        googleMapsUrl: mapsUrl("Pantheon Rome"),
        isInsideVisit: true,
      },
      {
        id: "d8-6",
        category: "sight",
        nameKo: "콜로세움",
        nameEn: "Colosseum",
        city: "로마",
        description: "서기 80년에 완공된 세계 최대의 원형 경기장. 외부 관광.",
        imagePath: "/images/rome/colosseum.jpg",
        googleMapsUrl: mapsUrl("Colosseum Rome"),
        isInsideVisit: false,
      },
      {
        id: "d8-7",
        category: "sight",
        nameKo: "포로 로마노",
        nameEn: "Roman Forum",
        city: "로마",
        description: "고대 로마의 정치·경제·종교의 중심지였던 광장 유적. 외부 관광.",
        imagePath: "/images/rome/roman-forum.jpg",
        googleMapsUrl: mapsUrl("Roman Forum Rome"),
        isInsideVisit: false,
      },
      {
        id: "d8-8",
        category: "sight",
        nameKo: "트레비 분수",
        nameEn: "Trevi Fountain",
        city: "로마",
        description: "동전을 던지면 로마에 다시 돌아온다는 전설의 분수. 바로크 양식의 웅장한 조각이 가득한 로마의 상징.",
        imagePath: "/images/rome/trevi-fountain.jpg",
        googleMapsUrl: mapsUrl("Trevi Fountain Rome"),
      },
      {
        id: "d8-9",
        category: "sight",
        nameKo: "비토리오 에마누엘레 2세 기념관",
        nameEn: "Altare della Patria",
        city: "로마",
        description: "이탈리아 통일을 기념하는 웅장한 기념관. '조국의 제단'이라고도 불리며 로마 시내 어디서도 보이는 백색 대리석 건물.",
        imagePath: "/images/rome/vittorio-emanuele.jpg",
        googleMapsUrl: mapsUrl("Altare della Patria Rome"),
      },
      {
        id: "d8-10",
        category: "optional",
        nameKo: "벤츠 밴 로마 투어 (선택관광)",
        city: "로마",
        description: "판테온, 진실의 입, 스페인 광장 등 시내 명소를 편안한 벤츠 밴을 타고 돌아보는 특별 투어.",
        googleMapsUrl: mapsUrl("Pantheon Rome"),
        priceEur: 70,
        duration: "약 3시간",
      },
      {
        id: "d8-11",
        category: "flight",
        time: "21:15",
        nameKo: "로마 피우미치노 공항 출발",
        nameEn: "Rome Fiumicino Airport FCO",
        city: "로마",
        description: "티웨이항공 TW0406편으로 인천으로 출발합니다. 비행 11시간 55분.",
        googleMapsUrl: mapsUrl("Rome Fiumicino Airport FCO"),
        duration: "비행 11시간 55분",
      },
    ],
  },
  {
    dayNumber: 9,
    date: "2026-07-04",
    dayOfWeek: "토",
    routeSummary: "인천 도착",
    breakfast: "기내식",
    lunch: "기내식",
    dinner: "없음",
    accommodationName: "귀국",
    accommodationGrade: "",
    accommodationStatus: "확정",
    spots: [
      {
        id: "d9-1",
        category: "flight",
        time: "16:10",
        nameKo: "인천국제공항 도착",
        nameEn: "Incheon International Airport",
        city: "인천",
        description: "인천국제공항 도착. 9일간의 이탈리아 아트 투어를 마칩니다.",
        imagePath: "/images/day1-cover.jpg",
        googleMapsUrl: mapsUrl("Incheon International Airport"),
      },
    ],
  },
];

export const OPTIONAL_TOURS = [
  { day: 5, name: "베네치아 수상택시", priceEur: 60, duration: "약 30분" },
  { day: 5, name: "베네치아 곤돌라", priceEur: 60, duration: "30~40분" },
  { day: 8, name: "벤츠 밴 로마 투어", priceEur: 70, duration: "약 3시간" },
];
